[package]
name = "vp_implicit"
description = "Implicit account valididity predicate."
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
namada_tx_prelude.workspace = true
namada_vp_prelude.workspace = true

rlsf.workspace = true
getrandom.workspace = true

[dev-dependencies]
namada_tests = {path = "../../crates/tests"}
namada_test_utils = {path = "../../crates/test_utils"}
namada_vp_prelude = {path = "../../crates/vp_prelude"}

proptest = "1.4.0"
test-log = {version = "0.2.14", default-features = false, features = ["trace"]}
tracing = "0.1.30"
tracing-subscriber = {version = "0.3.7", default-features = false, features = ["env-filter", "fmt"]}

[lib]
crate-type = ["cdylib"]
