[package]
name = "namada_vp"
description = "The Namada validity predicates native trait and host functions"
resolver = "2"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
namada_core = { path = "../core" }
namada_events = { path = "../events", default-features = false }
namada_gas = { path = "../gas" }
namada_storage = { path = "../storage" }
namada_tx = { path = "../tx" }
